spring.application.name=treeshopmanagingsystem
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=sa
spring.datasource.password=example
#TODO uncomment when migrating to docker
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
server.address=0.0.0.0
server.port=8080

# JWT config
#TODO remove when migrating to docker
jwt.secret=a-string-for-testing
jwt.lifetime=86400
jwt.cookie.name=hihi