spring.application.name=treeshopmanagingsystem
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=a-string-for-testing
jwt.lifetime=86400
jwt.cookie.name=hihi
spring.datasource.username=sa
spring.datasource.password=example
server.address=0.0.0.0
server.port=8080
