spring.application.name=treeshopmanagingsystem
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
JWT_SECRET=a-string-for-testing
JWT_LIFETIME=86400
spring.datasource.username=postgres
spring.datasource.password=example
server.address=0.0.0.0
server.port=8080
